attribute_type: string
is_transient: false
export: true
name: created_by
display_name: Created By
attribute_size: 255
default_value: current_user
description: User who the field/attribute was created by.
is_deprecated: false
is_required: true
is_unique: false