attribute_type: date_time
is_transient: false
export: true
name: created_at
display_name: Created At
attribute_size: 30
default_value: current_date_time
description: Date time when the field/attribute was created.
is_deprecated: false
is_required: true
is_unique: false